### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [lparam/xTun#1]
I would like to point out that identifiers like "[`_DAEMON_H`](https://github.com/lparam/xTun/blob/c846fdf48d21858579e3d1d04497ef41e301034c/src/daemon.h#L1)" and "[`_TUN_H`](https://github.com/lparam/xTun/blob/99d21de6b2bb7a8e041ed512a6624bd477e44d61/src/tun.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by lparam** [comment]
Already adjusted on develop branch.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/lparam/xTun/commit/adfbd673aeffeba536689ee6d1b387bc43c5a866 "Deletion of a few underscores").
