### ISSUE TITLE
Check return codes everywhere

### ISSUE THREAD

**Issue by elfring** [lparam/xTun#2]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output.") ⇒ [create_pidfile](https://github.com/lparam/xTun/blob/c846fdf48d21858579e3d1d04497ef41e301034c/src/daemon.c#L62)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [resolve_addr](https://github.com/lparam/xTun/blob/c846fdf48d21858579e3d1d04497ef41e301034c/src/util.c#L93)

**Comment by lparam** [comment]
It's not necessary for these cases.

**Comment by elfring** [comment]
I recommend to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?
