### ISSUE TITLE
How to use Xtun ?

### ISSUE THREAD

**Issue by esumit** [lparam/xTun#6]
Thanks for writing the great code, I just tried to use xTun with following steps 

**Step-1 : Clone it to my local and remote via git clone https://github.com/lparam/xTun.git**

My Local Config : 

192.168.1.4
root@esumit-docker:~/tunTap/xTun# lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

My remote Config :

IP Address :  138.197.18.245
osboxes@osboxes:~/work/TunTap/xTun$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Step-2 : After cloning : Installed these three packages** 

  611  sudo apt-get install libtool
  612  sudo apt-get install m4
  613  sudo apt-get install automake

**Step-3 : Compiled it via make && make install , all went well and i got xTun , See the last lines of log**

    CC src/util.o
    CC src/logger.o
    CC src/daemon.o
    CC src/signal.o
    CC src/crypto.o
    CC src/peer.o
    CC src/packet.o
    CC src/tcp.o
    CC src/tcp_client.o
    CC src/tcp_server.o
    CC src/udp.o
    CC src/tun.o
    CC src/main.o
    LINK xTun

**Step-4 : started server on remote host with following command** 

root@esumit-docker:~/tunTap/xTun# ./xTun -s -i tun0 -I 10.3.0.1/16 -k sumit -V -b 138.197.18.245 -n

Tun got created like 

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.3.0.1  P-t-P:10.3.0.1  Mask:255.255.0.0
          UP POINTOPOINT RUNNING  MTU:1426  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Step-5  Client Running on Local** 

sboxes@osboxes:~/work/TunTap/xTun$ sudo ./xTun -c 138.197.18.245  -i tun0 -I 10.3.0.2/16 -k sumit -V -n -t
2016/12/23 14:31:42 [ERR]: Connect to server failed: connection timed out
2016/12/23 14:33:59 [ERR]: Connect to server failed: connection timed out
2016/12/23 14:36:26 [ERR]: Connect to server failed: connection timed out
2016/12/23 14:39:13 [ERR]: Connect to server failed: connection timed out

Tun on Client 

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.3.0.2  P-t-P:10.3.0.2  Mask:255.255.0.0
          UP POINTOPOINT RUNNING  MTU:1426  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:840 (840.0 B)

IP Address of Local 

enp0s8    Link encap:Ethernet  HWaddr 08:00:27:d0:e3:c9  
          inet addr:192.168.1.4  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::6666:5cbc:b388:b586/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:23051 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18121 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:23930798 (23.9 MB)  TX bytes:1746536 (1.7 MB)

## **Step-6 - Ping 192.168.1.3 from remote , It doesn't work ???** 

root@esumit-docker:~# ping 192.168.1.3
PING 192.168.1.3 (192.168.1.3) 56(84) bytes of data.

## My questions : 

1.Its possible to ping from remote to local ip address as reverse tunnel ? 

2. Based on the above steps, what exactly is missing to see the funcitoning of this xTun ?

3. In verbose mode it doesn't show much logs ?

4. When we should use that script 

5. Any other documentation to refer , since it has very limited documentation

**Comment by lparam** [comment]
It looks like you can not access 138.197.18.245 from client?
If you want access a internal address via the tunnel, you should add a route entry like this:
```bash
 ip route add 192.168.1.3 via 10.3.0.1
```
I will fix the verbose log later.
No more documentation, please refer scripts under openwrt directory or read the source code, sorry about that.

**Comment by esumit** [comment]
May you please provide paid help on/around this ? (How to reach you ?)
