### ISSUE TITLE
xTun能否多实例运行，另外配合google的bbr加速似乎不稳定

### ISSUE THREAD

**Issue by wackejohn** [lparam/xTun#7]
你好，实际测试发现xTun无法多实例运行，有两个以上vps通过xTun做负载均衡应该如何实现呢？
另外在vps上启用了google的bbr加速，xTun运行在tcp模式下，有不错的加速效果（相对shadowvpn）但是在使用youtube测试时发现连接不稳定，几分钟之后就断线了，重启xTun客户端后恢复正常，-V模式貌似没有任何日志输出，不确定是否因为bbr本身不稳定还是xTun跟bbr不兼容？

**Comment by lparam** [comment]
可以多实例，指定不一样的设备名即可，如:
xTun -i tun0 -I 10.0.1.1/24  ...
xTun -i tun1 -I 10.0.2.1/24 ...

tcp模式下，断线会重新连接，跟BBR没关系。
-V参数的日志输出问题后面会作修改。

**Comment by lparam** [comment]
另外，关于多路出口的功能，目前还没这个打算。
