### ISSUE TITLE
加密方式是否需要改进

### ISSUE THREAD

**Issue by godwasdog** [lparam/xTun#8]
1、s~s现在靠拢AEAD了，加密方式是否需要改进？

2、NONCE 8byte是否短了些？

请看下面这两个链接
“Stream ciphers with IV length less than 12 bytes MUST be deprecated. Namely, bf-cfb, chacha20, and salsa20.”
https://github.com/shadowsocks/shadowsocks-org/issues/36
https://shadowsocks.org/en/spec/Stream-Ciphers.html

3、能否出win版？

**Comment by lparam** [comment]
1. 目前没必要。
2. 同上
3. 不出
